library(base, quietly = TRUE)
library(methods, quietly = TRUE)
library(datasets, quietly = TRUE)
library(utils, quietly = TRUE)
library(grDevices, quietly = TRUE)
library(graphics, quietly = TRUE)
library(stats, quietly = TRUE)
library(rslurm, quietly = TRUE)
.rslurm_func   <- readRDS('/home/vegayon/Documents/rslurm/vignettes/_rslurm_test_call/f.RDS')
.rslurm_params <- readRDS('/home/vegayon/Documents/rslurm/vignettes/_rslurm_test_call/params.RDS')
.rslurm_result <- do.call(.rslurm_func, .rslurm_params)
               
saveRDS(.rslurm_result, file = '/home/vegayon/Documents/rslurm/vignettes/_rslurm_test_call/results_0.RDS')
